/**
 * Everyday-language expansion: maps how people actually phrase questions onto
 * the vocabulary used in the knowledge base. Applied after stemming, so keys
 * and values should be written in their stemmed-ish base form.
 */
export const SYNONYMS: Record<string, string[]> = {
  // general intent words
  make: ["create", "define", "build", "write"],
  creat: ["create", "make", "define"],
  build: ["create", "make"],
  writ: ["write", "create", "define"],
  defin: ["define", "create"],
  declar: ["declare", "define", "assign", "variable"],
  add: ["append", "insert", "add"],
  delet: ["delete", "remove", "pop"],
  remov: ["remove", "delete", "pop"],
  chang: ["change", "modify", "update", "mutable"],
  modifi: ["modify", "change", "update"],
  fix: ["fix", "error", "debug"],
  broken: ["error", "bug", "fail"],
  crash: ["error", "exception", "traceback"],
  fail: ["error", "exception"],
  bug: ["error", "debug"],
  wrong: ["error", "mistake"],
  problem: ["error", "issue"],
  issu: ["error", "issue"],
  learn: ["basic", "beginner", "start"],
  start: ["basic", "beginner", "install"],
  beginn: ["basic", "beginner"],
  simpl: ["basic", "simple"],
  exampl: ["example", "code", "sample"],
  code: ["code", "example", "syntax"],
  syntax: ["syntax", "write", "code"],

  // structures
  array: ["list", "array", "sequence"],
  vector: ["list", "array"],
  map: ["dict", "dictionary", "map"],
  hashmap: ["dict", "dictionary"],
  hash: ["dict", "dictionary", "hashable"],
  object: ["object", "class", "instance"],
  instanc: ["instance", "object", "class"],
  blueprint: ["class", "object"],
  method: ["method", "function", "class"],
  func: ["function"],
  funct: ["function"],
  routin: ["function"],
  procedur: ["function"],
  paramet: ["parameter", "argument"],
  arg: ["argument", "parameter"],
  var: ["variable"],
  const: ["constant", "variable"],
  text: ["string", "str", "text"],
  str: ["string", "text"],
  number: ["int", "float", "number", "numeric"],
  numer: ["number", "int", "float"],
  integ: ["int", "integer", "number"],
  decim: ["float", "decimal", "number"],
  boolean: ["bool", "boolean", "true", "false"],
  null: ["none", "null", "empty"],
  nil: ["none", "null"],
  empti: ["empty", "none", "falsy"],
  key: ["key", "dict", "dictionary"],
  valu: ["value", "dict"],
  pair: ["key", "value", "dict", "tuple"],
  duplic: ["duplicate", "unique", "set"],
  uniqu: ["unique", "set", "duplicate"],

  // control flow
  condit: ["if", "condition", "conditional", "else"],
  branch: ["if", "condition", "conditional"],
  check: ["if", "condition", "test", "check"],
  compar: ["compare", "equality", "==", "condition"],
  repeat: ["loop", "for", "while", "iterate"],
  iterat: ["loop", "iterate", "for", "iterator"],
  loop: ["loop", "for", "while"],
  each: ["for", "loop", "iterate"],
  through: ["loop", "iterate"],
  over: ["loop", "iterate"],
  stop: ["break", "stop", "exit"],
  skip: ["continue", "skip"],
  exit: ["break", "return", "exit"],

  // errors
  error: ["error", "exception", "traceback"],
  except: ["exception", "error", "try"],
  traceback: ["error", "traceback", "exception"],
  handl: ["handle", "exception", "try", "catch"],
  catch: ["except", "catch", "exception", "try"],
  throw: ["raise", "exception"],
  rais: ["raise", "exception", "error"],

  // io / files
  file: ["file", "open", "read", "write"],
  save: ["write", "file", "save"],
  load: ["read", "load", "file", "open"],
  open: ["open", "file"],
  folder: ["directory", "folder", "path"],
  directori: ["directory", "folder", "path"],
  path: ["path", "file", "directory"],
  csv: ["csv", "file", "data"],
  json: ["json", "file", "data"],
  print: ["print", "output", "display"],
  displai: ["print", "output"],
  show: ["print", "output", "display"],
  input: ["input", "user", "read"],
  ask: ["input", "user"],

  // oop / modules
  inherit: ["inheritance", "subclass", "super", "parent"],
  parent: ["super", "inheritance", "parent"],
  child: ["subclass", "inheritance"],
  overrid: ["override", "inheritance", "method"],
  privat: ["private", "encapsulation", "underscore"],
  librari: ["module", "package", "import", "library"],
  packag: ["package", "module", "import", "pip"],
  modul: ["module", "import", "package"],
  import: ["import", "module"],
  instal: ["install", "pip", "package"],
  depend: ["dependency", "package", "pip", "requirements"],

  // misc topics
  speed: ["performance", "fast", "optimize"],
  fast: ["performance", "fast", "optimize"],
  slow: ["performance", "slow", "optimize"],
  memori: ["memory", "generator", "performance"],
  test: ["test", "pytest", "unittest", "assert"],
  debug: ["debug", "breakpoint", "error"],
  type: ["type", "datatype", "hint"],
  convert: ["convert", "cast", "type"],
  cast: ["cast", "convert", "type"],
  format: ["format", "fstring", "string"],
  regex: ["re", "regex", "pattern"],
  pattern: ["regex", "re", "pattern"],
  date: ["datetime", "date", "time"],
  time: ["time", "datetime"],
  random: ["random", "randint"],
  api: ["api", "http", "request", "json"],
  web: ["api", "http", "request"],
  request: ["request", "http", "api"],
  thread: ["thread", "concurrency", "parallel"],
  parallel: ["parallel", "thread", "async", "multiprocessing"],
  async: ["async", "await", "asyncio", "concurrency"],
  sort: ["sort", "sorted", "order"],
  order: ["sort", "sorted", "order"],
  revers: ["reverse", "sort", "slice"],
  count: ["count", "counter", "enumerate"],
  index: ["index", "enumerate", "position", "slice"],
  slice: ["slice", "index", "sublist"],
  copi: ["copy", "deepcopy", "reference"],
  scope: ["scope", "global", "local"],
  global: ["global", "scope"],
  recurs: ["recursion", "recursive"],
  decor: ["decorator", "wrapper"],
  generat: ["generator", "yield", "iterator"],
  yield: ["yield", "generator"],
  lambda: ["lambda", "anonymous", "function"],
  comprehens: ["comprehension", "list", "filter"],
  filter: ["filter", "comprehension"],
  best: ["best", "practice", "style", "pep8"],
  practic: ["practice", "style", "pep8"],
  style: ["style", "pep8", "convention"],
  name: ["name", "naming", "variable", "convention"],
  version: ["version", "install"],
  run: ["run", "execute", "install"],
  execut: ["run", "execute"],
};

/** Expand a stemmed token list with related knowledge-base vocabulary. */
export function expandTokens(tokens: string[]): string[] {
  const out = [...tokens];
  for (const t of tokens) {
    const extra = SYNONYMS[t] ?? SYNONYMS[t.replace(/e$/, "")] ?? SYNONYMS[`${t}e`];
    if (extra) out.push(...extra);
  }
  return out;
}
